# Form implementation generated from reading ui file 'tabela.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tabela(object):
    def setupUi(self, tabela):
        tabela.setObjectName("tabela")
        tabela.resize(437, 329)
        icon = QtGui.QIcon.fromTheme("applications-other")
        tabela.setWindowIcon(icon)
        self.pushButton = QtWidgets.QPushButton(parent=tabela)
        self.pushButton.setGeometry(QtCore.QRect(130, 261, 171, 41))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(tabela)
        QtCore.QMetaObject.connectSlotsByName(tabela)

    def retranslateUi(self, tabela):
        _translate = QtCore.QCoreApplication.translate
        tabela.setWindowTitle(_translate("tabela", "Tabela de estoque"))
        self.pushButton.setText(_translate("tabela", "Voltar"))
